### ISSUE TITLE
Feature Request: extend default config

### ISSUE THREAD

**Issue by haysclark** [conventionalcommit/commitlint#12]
It would be nice to have a smaller config file when only making small alterations to the Default Config of _commitlint_.  Adding a behavior allowing users to override the default config would allow for much smaller `.commitlint.yaml` files.

e.g.

```yaml
# .commitlint.yaml

extends: default
# or maybe
formatter: overwrite # or `extend`, 'overlay', 'merge', ...etc

# then just what values should be overwritten
settings:
  # Loosen up on the line lengths
  header-max-length:
    argument: 72
  body-max-line-length:
    argument: 100
  footer-max-line-length:
    argument: 100
```
