### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by rubensa** [conventionalcommit/commitlint#16]
**Node** [commitlint](https://github.com/conventional-changelog/commitlint) version seems to be the "de facto" standard [Conventional Commits](https://www.conventionalcommits.org/) linter (but it forces you to have node installed).

Are there any plans to make this project compatible with it?

I mean at:

- feature level
- [command](https://commitlint.js.org/#/reference-cli) parameter level
- [config](https://github.com/conventional-changelog/commitlint#config) file level

So it is easy to transition from the **Node** version to this **Go** version.

**Comment by rubensa** [comment]
My main concern is not much about missing features but [command line parameter](https://commitlint.js.org/reference/cli.html) and [configuration](https://commitlint.js.org/reference/configuration.html) compatibility.

For example, for default rules I need:

<details>

<summary>commitlint.config.js</summary>

```javascript
module.exports = { extends: ['@commitlint/config-conventional'] }
```

</details>

for **Node** commitlint.

But:

<details>

<summary>commitlint.config.yaml</summary>

```yaml
# https://github.com/conventionalcommit/commitlint?tab=readme-ov-file#default-config
version: v0.9.0
formatter: default
rules:
  - header-min-length
  - header-max-length
  - body-max-line-length
  - footer-max-line-length
  - type-enum
severity:
  default: error
settings:
  body-max-line-length:
    argument: 72
  footer-max-line-length:
    argument: 72
  header-min-length:
    argument: 10
  header-max-length:
    argument: 50
  type-enum:
    argument:
      - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
      - revert
```

</details>

for **Go** commitlint.

And I need to issue a **commit-msg** git hook like:

```bash
commitlint --config commitlint.config.js --edit .git/COMMIT_EDITMSG
```

for **Node** commitlint.

But:

```bash
commitlint lint --config commitlint.config.yaml < .git/COMMIT_EDITMSG
```

for **Go** commitlint.
